LANG = {
    'ENG': {
        'start'          :'Main menu:',
        'wallet'         : 'Wallet:',
        'top_10'         : 'Top 10 coins:',
        'search'         : 'Send me the coin short name, please. (e.j: BTC)',
        'search_error'   : '⚠️ Oops! I cant find this coin.',
        'settings'       : 'Your current settings:\n\nLanguage: {} \nCurrency: {}',
        'language'       : 'Choose your prefferred lenguage: ',
        'currency'       : 'Choose the currency in which you want the values ​​to be sent:',
        'b_wallet'       : "💰 Wallet",
        'b_search'       : "🔍 Search coin",
        'b_settings'     : "⚙️ Settings",
        'b_add_coin'     : "Add coin",
        'b_back_start'   : '<< back to main menu',
        'b_back_top_10'  : '<< back to Top 10',
        'b_back_wallet'  : '<< back to Wallet',
        'b_back_settings': '<< Back to settings',
        'b_update'       : 'Update',
        'b_cancel'       : 'Cancel',
        'b_retry'        : 'retry',
        'b_language'     : 'Language',
        'b_currency'     : 'Currency',
        #language
        'b_english'      : '🇬🇧 English',
        'b_spanish'      : '🇪🇸 Spanish'
    },
    'SPA': {
        'start'          :'Menú principal:',
        'wallet'         : 'Cartera:',
        'top_10'         : 'Monedas en el Top 10:',
        'search'         : 'Enviamé el nombre corto de la moneda, por favor. (e.j: BTC)',
        'search_error'   : '⚠️ Oops! No he podido encontrar esa moneda.',
        'settings'       : 'Tu configuración actual es:\n\nIdioma: {} \nMoneda: {}',
        'language'       : 'Elige tu idioma: ',
        'currency'       : 'Elige la moneda en la que quieres que te envíe los valores:',
        'b_wallet'       : "💰 Cartera",
        'b_search'       : "🔍 Buscar moneda",
        'b_settings'     : "⚙️ Configuración",
        'b_add_coin'     : "Añadir moneda",
        'b_back_start'   : '<< volver al menu principal',
        'b_back_top_10'  : '<< volver al Top 10',
        'b_back_wallet'  : '<< volver a tu Cartera',
        'b_back_settings': '<< volver a Configuracion',
        'b_update'       : 'Actualizar',
        'b_cancel'       : 'Cancelar',
        'b_retry'        : 'Reintentar',
        'b_language'     : 'Idioma',
        'b_currency'     : 'Moneda',
        #languages
        'b_english'      : '🇬🇧 Inglés',
        'b_spanish'      : '🇪🇸 Español'
    }
}
